---Secuencia para los id unicos de mascotas, usuarios, preguntas y respuestas.
CREATE SEQUENCE id_mascota        --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_persona        --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_adopcion       --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_devolucion     --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_pregunta       --APLICADO
  MINVALUE 0
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_respuesta      --APLICADO
  MINVALUE 0
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_telefono      --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_califica_a     --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE id_anade_a_lista_negra --APLICADO
  MINVALUE 0
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE id_foto_adopcion  --APLICADO
  MINVALUE 0
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE id_formulario     --APLICADO
  MINVALUE 0
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;

CREATE SEQUENCE id_bitacora       --APLICADO
  MINVALUE 0
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  