---Secuencia para los id únicos de mascotas, usuarios, preguntas y respuestas.
CREATE OR REPLACE SEQUENCE id_mascota
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;

CREATE OR REPLACE SEQUENCE id_usuario
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_adopcion
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_devolucion
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_pregunta
  MINVALUE 1
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_respuesta
  MINVALUE 1
  MAXVALUE 1000000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_telefono
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_califica_a
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
  
CREATE OR REPLACE SEQUENCE id_anade_a_lista_negra
  MINVALUE 1
  MAXVALUE 10000
  START WITH 0
  INCREMENT BY 1
  CACHE 20;
