/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_View;

/**
 *
 * @author Daniel
 */
public class MisMascotasAdoptada extends javax.swing.JFrame {

    /**
     * Creates new form MascotasAdoptadas
     */
    public MisMascotasAdoptada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleAdopciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAdopciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        verMascotaButton = new javax.swing.JButton();
        fotosMascotaButton = new javax.swing.JButton();
        verRescatistaButton = new javax.swing.JButton();
        devolverMascotaButton = new javax.swing.JButton();
        atrasButton = new javax.swing.JButton();
        javax.swing.JLabel enunciadoLabel = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titleAdopciones.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        titleAdopciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAdopciones.setText("Adopciones realizadas");
        getContentPane().add(titleAdopciones);
        titleAdopciones.setBounds(0, 4, 720, 30);

        tablaAdopciones.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        tablaAdopciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Rescatista", "Tipo", "Raza", "Fecha"
            }
        ));
        tablaAdopciones.setOpaque(false);
        jScrollPane1.setViewportView(tablaAdopciones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 452, 160);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Opciones adopción", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Rockwell", 1, 18))); // NOI18N
        jPanel1.setOpaque(false);

        verMascotaButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        verMascotaButton.setText("Ver Mascota");
        verMascotaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verMascotaButton.setContentAreaFilled(false);
        jPanel1.add(verMascotaButton);

        fotosMascotaButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        fotosMascotaButton.setText("Subir fotos de la mascota");
        fotosMascotaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fotosMascotaButton.setContentAreaFilled(false);
        jPanel1.add(fotosMascotaButton);

        verRescatistaButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        verRescatistaButton.setText("¿Quién rescató a la mascota?");
        verRescatistaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verRescatistaButton.setContentAreaFilled(false);
        jPanel1.add(verRescatistaButton);

        devolverMascotaButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        devolverMascotaButton.setText("Devolver Mascota");
        devolverMascotaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        devolverMascotaButton.setContentAreaFilled(false);
        devolverMascotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverMascotaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(devolverMascotaButton);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(480, 130, 220, 160);

        atrasButton.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        atrasButton.setText("Atrás");
        getContentPane().add(atrasButton);
        atrasButton.setBounds(580, 300, 120, 30);

        enunciadoLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        enunciadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enunciadoLabel.setText("<html><body> En esta ventana se administran las adopciones realizadas por el usuario. Puede ver las mascotas que ha adoptado, el perfil de rescatista de las mascotas, así como subir fotos de la mascota luego de la adopción y bajo su cuidado. Si por una razón, ya no puede mantener a la mascota, puede devolverla al rescatista presionando \"Devolver Mascota\".");
        getContentPane().add(enunciadoLabel);
        enunciadoLabel.setBounds(10, 40, 700, 70);
        enunciadoLabel.setText("<html>En esta ventana se muestra las mascotas que usted ha adoptado hasta el momento. Seleccione una fila de la tabla para poder ver a opciones más avanzadas.</html>");

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_View/Images/adopcion.jpg"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 720, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void devolverMascotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverMascotaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_devolverMascotaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisMascotasAdoptada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisMascotasAdoptada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisMascotasAdoptada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisMascotasAdoptada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisMascotasAdoptada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton atrasButton;
    private javax.swing.JLabel backgroundImage;
    public javax.swing.JButton devolverMascotaButton;
    public javax.swing.JButton fotosMascotaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaAdopciones;
    public javax.swing.JLabel titleAdopciones;
    public javax.swing.JButton verMascotaButton;
    public javax.swing.JButton verRescatistaButton;
    // End of variables declaration//GEN-END:variables
}
